name: 'auto-version-node'
description: 'Github Action to auto-increment Node package version'
inputs:
  access-token:  # Repo access token
    description: 'GitHub Repo access token'
    required: true
  branch-name:  # Feature branch to use
    description: 'The name of the branch'
    required: true
  package-version:  # Package version updating to
    description: 'The package version updating to'
    required: false
    default: 'Unknown'
runs:
  using: 'node12'
  main: 'dist/index.js'
